package com.company;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.event.KeyEvent;
import java.io.File;

public class StackFrame extends javax.swing.JFrame {

    private final JFileChooser openFileChooser;

    static Stack<Integer> st = new Stack<>();
    OpenStack L = new OpenStack();
    LoadStack L1 = new LoadStack();

    /**
     * Creates new form StackFrame
     */
    public StackFrame() {
        super("Stack Project");
        initComponents();
        openFileChooser = new JFileChooser();
        openFileChooser.setCurrentDirectory(new File("D:\\"));
        openFileChooser.setFileFilter(new FileNameExtensionFilter("txt Text", "txt"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LablePush = new javax.swing.JLabel();
        PushField = new javax.swing.JTextField();
        LabelSize = new javax.swing.JLabel();
        PushButton = new javax.swing.JButton();
        LableErorrpush = new javax.swing.JLabel();
        LablePop = new javax.swing.JLabel();
        PopButton = new javax.swing.JButton();
        LableErorrpop = new javax.swing.JLabel();
        LablePeek = new javax.swing.JLabel();
        PeekData = new javax.swing.JLabel();
        PeekButton = new javax.swing.JButton();
        LableErorrpeek = new javax.swing.JLabel();
        LabelStackis = new javax.swing.JLabel();
        LableSort = new javax.swing.JLabel();
        SortButton = new javax.swing.JButton();
        printSorted = new javax.swing.JLabel();
        LabelErorrSort = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LoadLabel = new javax.swing.JLabel();
        LoadField = new javax.swing.JTextField();
        LoadButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);

        LablePush.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LablePush.setText("Push:");

        PushField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PushFieldActionPerformed(evt);
            }
        });
        PushField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                PushFieldKeyPressed(evt);
            }
        });

        LabelSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelSize.setText("Stack is initially empty.");

        PushButton.setText("Push");
        PushButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PushButtonActionPerformed(evt);
            }
        });

        LablePop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LablePop.setText("Pop:");

        PopButton.setText("POP");
        PopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopButtonActionPerformed(evt);
            }
        });

        LablePeek.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LablePeek.setText("Peek:");

        PeekData.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        PeekData.setForeground(new java.awt.Color(51, 0, 255));

        PeekButton.setText("Peek");
        PeekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeekButtonActionPerformed(evt);
            }
        });

        LabelStackis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelStackis.setText("Stack Is :");

        LableSort.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LableSort.setText("Sort Ascending:");

        SortButton.setText("Sort");
        SortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortButtonActionPerformed(evt);
            }
        });

        printSorted.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        printSorted.setText("Sorted Stack :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LablePeek)
                                        .addGap(18, 18, 18)
                                        .addComponent(PeekData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LablePush)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PushField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LablePop)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PushButton, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(PeekButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LableErorrpeek, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LableErorrpush, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LableErorrpop, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(234, 234, 234))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(printSorted, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LableSort)
                                .addGap(18, 18, 18)
                                .addComponent(SortButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelErorrSort, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelStackis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelStackis, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LableErorrpush, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LablePush, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PushField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PushButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PeekButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LablePeek, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PeekData, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LableErorrpeek, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LablePop, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LableErorrpop, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelErorrSort, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LableSort, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SortButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printSorted, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LoadLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        LoadLabel.setText("Load File");

        LoadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadFieldActionPerformed(evt);
            }
        });
        LoadField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                LoadFieldKeyPressed(evt);
            }
        });

        LoadButton.setText("Open...");
        LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LoadLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LoadField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoadField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel1.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortButtonActionPerformed
        if (st.isEmpty()) {
            LabelErorrSort.setText("No elements to sort !!");
        }
        printSorted.setText("Sorted Stack : " + st.sortAscending(st));
    }//GEN-LAST:event_SortButtonActionPerformed

    private void PeekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeekButtonActionPerformed
        if (st.isEmpty()) {
            LableErorrpeek.setText("Empty Stack Can't Peek !!");
        } else {
            String data = "" + st.peek();
            PeekData.setText(data);
            LableErorrpeek.setText("peek is done");
        }
    }//GEN-LAST:event_PeekButtonActionPerformed

    private void PopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopButtonActionPerformed
        if (st.isEmpty()) {
            LableErorrpop.setText("Empty Stack Can't Pop !!");
        } else {
            st.pop();
            LableErorrpop.setText("pop is done");
            LabelSize.setText("Size is = " + st.getsize());
            LabelStackis.setText("Stack is : " + st.toString());
        }
    }//GEN-LAST:event_PopButtonActionPerformed

    private void PushButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PushButtonActionPerformed
        int item = 0;
        try {
            item = Integer.parseInt(PushField.getText());
            st.push(item);
            PushField.setText("");
            if (st.peek() == item) {
                LableErorrpush.setText("Pushed");
            }
        } catch (NumberFormatException e) {
            LableErorrpush.setText("Must Be Integer!");
            PushField.setText("");
        }

        LabelSize.setText("Size is = " + st.getsize());
        LabelStackis.setText("Stack is : " + st.toString());
        PushField.setText("");
    }//GEN-LAST:event_PushButtonActionPerformed

    private void PushFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PushFieldActionPerformed

    }//GEN-LAST:event_PushFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = LoadField.getText();
        try {
            LoadStack.load(path);
            LoadLabel.setText("File opened successfully");
            st = LoadStack.load(path);
            LabelStackis.setText("Stack Is : " + st.toString());
            LabelSize.setText("Size is = " + st.getsize());
            LoadField.setText("");
        } catch (Exception e) {
            LoadLabel.setText("Try agian , Error whith path");
            LoadField.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtonActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {

            String path = LoadField.getText();
            try {
                File selectedFile = openFileChooser.getSelectedFile();
                OpenStack.load(selectedFile);
                LoadLabel.setText("File opened successfully");
                st = OpenStack.load(selectedFile);
                LabelStackis.setText("Stack Is : " + st.toString());
                LabelSize.setText("Size is = " + st.getsize());
                LoadField.setText("");
            } catch (Exception e) {
                LoadLabel.setText("Try agian , Error whith path");
                LoadField.setText("");
            }

        } else {
            LoadLabel.setText("Try agian , File Not Choosen");
        }

    }//GEN-LAST:event_LoadButtonActionPerformed

    private void LoadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadFieldActionPerformed

    private void LoadFieldKeyPressed(KeyEvent evt) {//GEN-FIRST:event_LoadFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String path = LoadField.getText();
            try {
                LoadStack.load(path);
                LoadLabel.setText("File opened successfully");
                st = LoadStack.load(path);
                LabelStackis.setText("Stack Is : " + st.toString());
                LabelSize.setText("Size is = " + st.getsize());
                LoadField.setText("");
            } catch (Exception e) {
                LoadLabel.setText("Try agian , Error whith path");
                LoadField.setText("");
            }

        }
    }//GEN-LAST:event_LoadFieldKeyPressed

    private void PushFieldKeyPressed(KeyEvent evt) {//GEN-FIRST:event_PushFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            int item = 0;
            try {
                item = Integer.parseInt(PushField.getText());
                st.push(item);
                PushField.setText("");
            } catch (NumberFormatException e) {
                LableErorrpush.setText("Must Be Integer!");
                PushField.setText("");
            }
            if (st.peek() == item) {
                LableErorrpush.setText("Pushed");
            }

            LabelSize.setText("Size is = " + st.getsize());
            LabelStackis.setText("Stack is : " + st.toString());
            PushField.setText("");

        }
    }//GEN-LAST:event_PushFieldKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StackFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StackFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StackFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StackFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StackFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelErorrSort;
    private javax.swing.JLabel LabelSize;
    public javax.swing.JLabel LabelStackis;
    private javax.swing.JLabel LableErorrpeek;
    private javax.swing.JLabel LableErorrpop;
    private javax.swing.JLabel LableErorrpush;
    private javax.swing.JLabel LablePeek;
    private javax.swing.JLabel LablePop;
    private javax.swing.JLabel LablePush;
    private javax.swing.JLabel LableSort;
    private javax.swing.JButton LoadButton;
    private javax.swing.JTextField LoadField;
    private javax.swing.JLabel LoadLabel;
    private javax.swing.JButton PeekButton;
    private javax.swing.JLabel PeekData;
    private javax.swing.JButton PopButton;
    public javax.swing.JButton PushButton;
    public javax.swing.JTextField PushField;
    private javax.swing.JButton SortButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel printSorted;
    // End of variables declaration//GEN-END:variables
}
